uploads = []
outputs = []

[[generated]]
id = "nz3eIBXIEy_gVRE0MFDOt"
uri = "file://artifacts/channel-site/public/images/logo.png"
type = "image"
title = "Cinema Prime Logo"

[[generated]]
id = "kior_2vTqDEYZbF4op_cK"
uri = "file://artifacts/channel-site/public/images/poster1.png"
type = "image"
title = "Sci-Fi Space Poster"

[[generated]]
id = "QLF1WyxFSLRRKttPcT9Zs"
uri = "file://artifacts/channel-site/public/images/poster2.png"
type = "image"
title = "Detective Noir Poster"

[[generated]]
id = "zk24pjSM8O8kz52Nx0v1V"
uri = "file://artifacts/channel-site/public/images/poster3.png"
type = "image"
title = "Fantasy Epic Poster"

[[generated]]
id = "xk30QTk3lx8gl7sgynmUu"
uri = "file://artifacts/channel-site/public/images/poster4.png"
type = "image"
title = "Historical Drama Poster"

[[generated]]
id = "hmQXHa6Qevq-OjILzETwA"
uri = "file://artifacts/channel-site/public/images/poster5.png"
type = "image"
title = "Horror Thriller Poster"

[[generated]]
id = "qncYOzjypXFjHlS4X6sio"
uri = "file://artifacts/channel-site/public/images/poster6.png"
type = "image"
title = "Cyberpunk Action Poster"
